services:
  client:
    image: ghcr.io/adibarra/shadle/client:latest
    ports:
      - '3000:80'
    restart: unless-stopped
    depends_on:
      - server
    healthcheck:
      test: [CMD, wget, --quiet, --tries=1, --spider, 'http://localhost']
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 20s

  server:
    image: ghcr.io/adibarra/shadle/server:latest
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    depends_on:
      - postgres
    healthcheck:
      test: [CMD, wget, --quiet, --tries=1, --spider, 'http://localhost:81/api/health']
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - '3002:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s

volumes:
  postgres-data:
